import { GameEvent } from '@/types/events';

export const mockEvents: GameEvent[] = [
  {
    id: '1',
    title: 'Summer Championship',
    description: 'Compete in the ultimate summer tournament for exclusive rewards',
    type: 'seasonal',
    gameId: 1,
    gameName: 'Valorant',
    bannerImage: 'https://picsum.photos/seed/event1/1200/300',
    startDate: Date.now() - 86400000 * 5,
    endDate: Date.now() + 86400000 * 9,
    active: true,
    rewards: [
      {
        id: 'r1',
        name: 'Golden Dragon Skin',
        description: 'Exclusive limited edition weapon skin',
        type: 'skin',
        image: 'https://picsum.photos/seed/reward1/200/200',
        rarity: 'legendary',
        requirement: 'Complete all challenges',
      },
      {
        id: 'r2',
        name: 'Champion Badge',
        description: 'Display your championship status',
        type: 'badge',
        image: 'https://picsum.photos/seed/reward2/200/200',
        rarity: 'exclusive',
        requirement: 'Top 100 on leaderboard',
      },
      {
        id: 'r3',
        name: 'Summer Emote Pack',
        description: '5 exclusive summer-themed emotes',
        type: 'emote',
        image: 'https://picsum.photos/seed/reward3/200/200',
        rarity: 'epic',
        requirement: 'Earn 5000 event points',
      },
      {
        id: 'r4',
        name: 'Premium Loot Box',
        description: 'Contains rare items and currency',
        type: 'lootbox',
        image: 'https://picsum.photos/seed/reward4/200/200',
        rarity: 'rare',
        requirement: 'Participate in 10 matches',
      },
    ],
    challenges: [
      {
        id: 'c1',
        title: 'Win 10 Matches',
        description: 'Win 10 ranked matches during the event',
        progress: 7,
        target: 10,
        points: 1000,
        completed: false,
      },
      {
        id: 'c2',
        title: 'Get 50 Kills',
        description: 'Eliminate 50 enemies in event matches',
        progress: 50,
        target: 50,
        points: 500,
        completed: true,
      },
      {
        id: 'c3',
        title: 'Play with Friends',
        description: 'Play 5 matches with clan members',
        progress: 3,
        target: 5,
        points: 750,
        completed: false,
      },
      {
        id: 'c4',
        title: 'Achieve 5 MVPs',
        description: 'Be the MVP in 5 different matches',
        progress: 2,
        target: 5,
        points: 1500,
        completed: false,
      },
      {
        id: 'c5',
        title: 'Daily Login Streak',
        description: 'Log in for 7 consecutive days',
        progress: 5,
        target: 7,
        points: 800,
        completed: false,
      },
    ],
    participants: 45678,
    leaderboard: [
      {
        rank: 1,
        userId: '101',
        username: 'EventMaster',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=EventMaster',
        points: 15750,
        completedChallenges: 12,
      },
      {
        rank: 2,
        userId: '102',
        username: 'ChampionX',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ChampionX',
        points: 14230,
        completedChallenges: 11,
      },
      {
        rank: 3,
        userId: '103',
        username: 'ProGamer99',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ProGamer99',
        points: 13890,
        completedChallenges: 10,
      },
      {
        rank: 4,
        userId: '104',
        username: 'ElitePlayer',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ElitePlayer',
        points: 12560,
        completedChallenges: 10,
      },
      {
        rank: 5,
        userId: '105',
        username: 'ShadowNinja',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ShadowNinja',
        points: 11340,
        completedChallenges: 9,
      },
    ],
  },
  {
    id: '2',
    title: 'Halloween Spooktacular',
    description: 'Spooky challenges and haunting rewards await',
    type: 'holiday',
    gameId: 2,
    gameName: 'League of Legends',
    bannerImage: 'https://picsum.photos/seed/event2/1200/300',
    startDate: Date.now() + 86400000 * 30,
    endDate: Date.now() + 86400000 * 44,
    active: false,
    rewards: [],
    challenges: [],
    participants: 0,
    leaderboard: [],
  },
];
