import { PlayerRanking, MatchResult } from '@/types/ranking';

export const mockPlayerRanking: PlayerRanking = {
  userId: '1',
  username: 'ProGamer123',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ProGamer123',
  gameId: 1,
  gameName: 'Valorant',
  tier: 'platinum',
  division: 2,
  elo: 1750,
  wins: 145,
  losses: 98,
  winRate: 59.67,
  streak: 5,
  peakElo: 1890,
  rank: 1247,
  region: 'NA',
};

export const mockRecentMatches: MatchResult[] = [
  {
    id: '1',
    gameId: 1,
    result: 'win',
    eloChange: 25,
    kda: '18/5/12',
    mvp: true,
    timestamp: Date.now() - 3600000,
  },
  {
    id: '2',
    gameId: 1,
    result: 'win',
    eloChange: 22,
    kda: '15/8/9',
    mvp: false,
    timestamp: Date.now() - 7200000,
  },
  {
    id: '3',
    gameId: 1,
    result: 'loss',
    eloChange: -18,
    kda: '12/14/7',
    mvp: false,
    timestamp: Date.now() - 86400000,
  },
  {
    id: '4',
    gameId: 1,
    result: 'win',
    eloChange: 24,
    kda: '21/6/15',
    mvp: true,
    timestamp: Date.now() - 172800000,
  },
  {
    id: '5',
    gameId: 1,
    result: 'win',
    eloChange: 20,
    kda: '14/9/11',
    mvp: false,
    timestamp: Date.now() - 259200000,
  },
];

export const mockLeaderboard: PlayerRanking[] = [
  {
    userId: '101',
    username: 'ChampionX',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ChampionX',
    gameId: 1,
    gameName: 'Valorant',
    tier: 'challenger',
    division: 1,
    elo: 3456,
    wins: 523,
    losses: 198,
    winRate: 72.54,
    streak: 12,
    peakElo: 3567,
    rank: 1,
    region: 'NA',
  },
  {
    userId: '102',
    username: 'LegendKiller',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LegendKiller',
    gameId: 1,
    gameName: 'Valorant',
    tier: 'grandmaster',
    division: 4,
    elo: 3189,
    wins: 467,
    losses: 234,
    winRate: 66.62,
    streak: -2,
    peakElo: 3289,
    rank: 2,
    region: 'NA',
  },
  {
    userId: '103',
    username: 'MasterAce',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MasterAce',
    gameId: 1,
    gameName: 'Valorant',
    tier: 'grandmaster',
    division: 3,
    elo: 3045,
    wins: 401,
    losses: 256,
    winRate: 61.02,
    streak: 7,
    peakElo: 3145,
    rank: 3,
    region: 'NA',
  },
  {
    userId: '104',
    username: 'ShadowElite',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ShadowElite',
    gameId: 1,
    gameName: 'Valorant',
    tier: 'grandmaster',
    division: 1,
    elo: 2890,
    wins: 378,
    losses: 289,
    winRate: 56.65,
    streak: 3,
    peakElo: 2990,
    rank: 4,
    region: 'NA',
  },
  {
    userId: '105',
    username: 'DiamondPro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=DiamondPro',
    gameId: 1,
    gameName: 'Valorant',
    tier: 'master',
    division: 4,
    elo: 2756,
    wins: 345,
    losses: 267,
    winRate: 56.37,
    streak: -1,
    peakElo: 2856,
    rank: 5,
    region: 'NA',
  },
];
